# Generated by Django 4.2.11 on 2026-01-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='provider',
        ),
    ]
