# Generated by Django 4.2.11 on 2026-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_avatar_url_remove_profile_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User'), ('gym_owner', 'Gym Owner'), ('admin', 'Admin')], db_index=True, default='user', max_length=20),
        ),
    ]
