# Generated by Django 4.2.11 on 2026-01-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_is_premium_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
