# Generated by Django 4.2.11 on 2026-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_is_premium_remove_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('GYM_OWNER', 'Gym Owner')], default='USER', max_length=20),
        ),
    ]
