# Generated by Django 4.2.11 on 2026-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymownerprofile',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('PRO', 'Pro')], default='FREE', max_length=20),
        ),
    ]
