# Generated by Django 6.0 on 2025-12-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_healthdata_id_alter_workout_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('sets', models.IntegerField()),
                ('reps', models.CharField(max_length=20)),
                ('rest_seconds', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_muscle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=15)),
                ('focus', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.goal')),
            ],
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='user',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.exercise'),
        ),
        migrations.AddField(
            model_name='dayexercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workoutday'),
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
    ]
