# Generated by Django 4.2.11 on 2026-01-05 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0003_dayexercise_exercise_goal_workoutday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate in BPM', null=True)),
                ('calories_consumed', models.PositiveIntegerField(default=0)),
                ('water_intake_ml', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
