# Generated by Django 4.2.11 on 2026-01-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explore', '0003_category_useractivity_trainer_exploreworkout_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exploreworkout',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exploreworkout',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbookmark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='article',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='explore.trainer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(default='General Fitness', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='explore.trainer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/banners/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ExploreWorkout',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.DeleteModel(
            name='UserBookmark',
        ),
        migrations.AddField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='explore.event'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='explore.challenge'),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('user', 'challenge')},
        ),
    ]
