# Generated by Django 4.2.11 on 2026-01-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0005_gym_is_verified_gym_logo_gym_owner_gym_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='secondary_color',
        ),
        migrations.DeleteModel(
            name='GymMember',
        ),
    ]
