# Generated by Django 4.2.11 on 2026-01-05 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list, help_text='List of features as JSON array'),
        ),
    ]
