# Generated by Django 4.2.11 on 2026-01-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_sharedworkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedWorkout',
        ),
    ]
